(feat): NCDate 기능 추가 - getStringWithTimezone : 타임존과 포멧을 받아 스트링 리턴
ncodeofficial/ncode_react_lib pull request #6
Opened 2022-03-17 10:33 UTC by SungKyungPark

getStringWithTimezone(timezone:string, format:string) : string

format을 넣지 않으면 FORMAT_UTC_ISO 에 의해 timezone이 무시되므로 필수값으로 지정하였습니다.

2022-03-18 01:54 UTC, iamchiwon-ncode requested changes
테스트 코드로 함께 있으면 좋겠는데요.

2022-03-18 01:54 UTC, iamchiwon-ncode commented on src/utils/date/NCDate.ts
> +  getStringWithTimezone(timezone: string, format: string): string {
timezone 에 이상한 값을 넣으면 어떻게 됩니까? "jeju-kr" 이런거요.
enum TimeZone 을 만들고 그 타입으로 받아들이면 어떨까요?

2022-03-21 05:17 UTC, SungKyungPark commented on src/utils/date/NCDate.ts
> +  getStringWithTimezone(timezone: string, format: string): string {
enum TimeZone 추가하였습니다.

2022-03-21 05:21 UTC, SungKyungPark commented
JSDateDating test 에 추가기능(getStringWithTimezone) 테스트 코드 작성하였습니다.

2022-03-23 04:53 UTC, merged